{{- range $service, $config := .Values.services }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Release.Name }}-{{ $service }}
  labels:
    hi: there
spec:
  type: {{ $config.type }}
  ports:
    {{- range $port := $config.ports}}
    - name: {{ $port.name }}
      protocol: {{ $port.protocol }}
      port: {{ $port.port }}
      targetPort: {{ $port.targetPort }}
    {{- end }}
  selector:
    app: {{ $.Release.Name }}-{{ $service }}
{{- end }}
